apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: job-api
  template:
    metadata:
      labels:
        app: job-api
    spec:
      containers:
        - name: job-api
          image: job-aggregator-api:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: job-aggregator-env
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: job-aggregator-data
---
apiVersion: v1
kind: Service
metadata:
  name: job-api
spec:
  selector:
    app: job-api
  ports:
    - port: 8000
      targetPort: 8000

