fullnameOverride: crawler-api
replicaCount: 1
image:
  repository: job-aggregator-crawler-api
  tag: replace-with-git-sha
containerPorts:
  - name: http
    containerPort: 8200
service:
  enabled: true
  port: 8200
  targetPort: 8200
env:
  - name: CRAWL_BACKEND
    value: http
envFrom:
  - secretRef:
      name: job-aggregator-env
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 512Mi
readinessProbe:
  httpGet:
    path: /api/v1/health
    port: 8200
livenessProbe:
  httpGet:
    path: /api/v1/health
    port: 8200
